# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBHServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='qFourResponse',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='entry',
            name='qOneResponse',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='entry',
            name='qThreeResponse',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='entry',
            name='qTwoResponse',
            field=models.IntegerField(default=1),
        ),
    ]
